# Dependencies
markdown:         redcarpet
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            VM for Homer Multitext project editors
tagline:          'A complete system for editing and validating HMT work'
description:      'Current version of the HMT project VM for editors'
baseurl: '/editors-vm/'



author:
  name:           'Neel Smith'

paginate:         5

links:
  - title: Documentation
    url: http://homermultitext.github.io/hmt-docs/vm/
    external: true
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: HMT editors' group
    url: http://hmteditors.github.io/
    external: true
  - title: HMT home page
    url: http://www.homermultitext.org/
    external: true
  - title: Github source for this site
    url: https://github.com/homermultitext/editors-vm
    external: true
